@host = localhost:3007
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTA2ODc3MzMsImV4cCI6MTcxMDc3MDUzMywic3ViIjoiMiJ9.f5MKNVaUSlTif_KSSNOf_z4mETEDXqOYPkHbNC4DwxU

GET http://{{host}}/questions/binary/2023-08-31/2024-03-12
Content-Type: application/json
Authorization: {{token}}
###

GET http://{{host}}/questions/flex/2023-08-31/2024-03-17
Content-Type: application/json
Authorization: {{token}}