# create new user
POST http://localhost:3007/customer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDc1ODI4MTUsImV4cCI6MTcwNzY2NTYxNSwic3ViIjoiMiJ9.XF2EJ1s5SiIIr3DiFGju30s8x9O1Lb_MEjxsobg0A2c

{
	"first_name": "Rodolfo",
	"surname": "Canela",
	"position": "GERENTE",
	"phone": "(61) 996778575",
	"email": "rodolfo@gmail.com",
	"password": "@senha123",
	"accept_terms": 1,
	"type_customer": 4,
	"company": 2
}
### end

# delete user
DELETE http://localhost:3007/customer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDc1ODI4MTUsImV4cCI6MTcwNzY2NTYxNSwic3ViIjoiMiJ9.XF2EJ1s5SiIIr3DiFGju30s8x9O1Lb_MEjxsobg0A2c

{
	"id": 12,
	"email": "pediegoss@gmail.com",
	"password": "@senha123"
}
###

GET http://localhost:3007/list/customer/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDc1ODI4MTUsImV4cCI6MTcwNzY2NTYxNSwic3ViIjoiMiJ9.XF2EJ1s5SiIIr3DiFGju30s8x9O1Lb_MEjxsobg0A2c
###

GET http://localhost:3007/type/customer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDc1ODI4MTUsImV4cCI6MTcwNzY2NTYxNSwic3ViIjoiMiJ9.XF2EJ1s5SiIIr3DiFGju30s8x9O1Lb_MEjxsobg0A2c
###