# create new user
POST http://localhost:3007/customer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDc0Mzg3ODEsImV4cCI6MTcwNzUyMTU4MSwic3ViIjoiMiJ9.rI9APKXHKcXHdDXNHJEkNUpl-Tkwpiz4_-RXs-l1KAs

{
	"first_name": "Rodolfo",
	"surname": "Canela",
	"position": "GERENTE",
	"phone": "(61) 996778575",
	"email": "rodolfo@gmail.com",
	"password": "@senha123",
	"accept_terms": 1,
	"type_customer": 4,
	"company": 2
}
### end

# delete user
DELETE http://localhost:3007/customer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDc0Mzg3ODEsImV4cCI6MTcwNzUyMTU4MSwic3ViIjoiMiJ9.rI9APKXHKcXHdDXNHJEkNUpl-Tkwpiz4_-RXs-l1KAs

{
	"id": 12,
	"email": "pediegoss@gmail.com",
	"password": "@senha123"
}
###

GET http://localhost:3007/list/customer/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDc1MDI2NDksImV4cCI6MTcwNzU4NTQ0OSwic3ViIjoiMiJ9.KPxs1j-Mj9VWBscOyetRXyzzOYgeZMw3BG0nOQEsvnc
###