@host = localhost:3007
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTU5NzY3MTksImV4cCI6MTcxNjA1OTUxOSwic3ViIjoiMiJ9.HIu-Xj7WqbZDbDBHDUXhIOO9Ieb34ySSr10gI3mijSQ

GET http://{{host}}/list/customer/company
Content-Type: application/json
Authorization: {{token}}
###

### test permission urls
GET http://{{host}}/has-company
Content-Type: application/json
Authorization: {{token}}
###

GET http://{{host}}/details
Content-Type: application/json
Authorization: {{token}}
###

GET http://{{host}}/multi-store
Content-Type: application/json
Authorization: {{token}}
###

GET http://{{host}}/details
Content-Type: application/json
Authorization: {{token}}
###

GET http://{{host}}/avatar
Content-Type: application/json
Authorization: {{token}}
###

GET http://{{host}}/type/customer
Content-Type: application/json
Authorization: {{token}}
###
### test permission urls

GET http://{{host}}/multi-store
Content-Type: application/json
Authorization: {{token}}
###

GET http://{{host}}/dashboard/department/2024-02-22/2024-02-29/1
Content-Type: application/json
Authorization: {{token}}
###

GET http://{{host}}/dashboard/amount/research
Content-Type: application/json
Authorization: {{token}}
###

GET http://{{host}}/avatar
Content-Type: application/json
Authorization: {{token}}
###

GET http://{{host}}/type/customer
Content-Type: application/json
Authorization: {{token}}
###

GET http://{{host}}/company-questions
Content-Type: application/json
Authorization: {{token}}
###

GET http://{{host}}/details
Content-Type: application/json
Authorization: {{token}}
###

GET http://{{host}}/list/store
Content-Type: application/json
Authorization: {{token}}
###

GET http://{{host}}/list/type/customers
Content-Type: application/json
Authorization: {{token}}
###

DELETE http://{{host}}/customer
Content-Type: application/json
Authorization: {{token}}

{
	"id": 5
}
###

DELETE http://{{host}}/customer
Content-Type: application/json
Authorization: {{token}}

{
	"email": "joerlison@gmail.com",
	"password": "@senha123"
}
###

POST http://{{host}}/join/role/customer
Content-Type: application/json
Authorization: {{token}}

{
	"role_id": 1,
	"customer_id": 2
}
###

PATCH http://{{host}}/update/role/customer
Content-Type: application/json
Authorization: {{token}}

{
	"role_id": 2,
	"customer_id": 2
}
###

POST http://{{host}}/join/role/customer
Content-Type: application/json
Authorization: {{token}}

{
	"role_id": 1,
	"customer_id": 2
}
###

POST http://{{host}}/join/customer/permissions
Content-Type: application/json
Authorization: {{token}}

{
	"customer_id": 2,
	"permissions": [1, 2, 3, 4, 5]
}
###

PUT http://{{host}}/update/customer/permissions
Content-Type: application/json
Authorization: {{token}}

{
	"customer_id": 2,
	"permissions": [1, 2, 3]
}
###

GET http://{{host}}/question
Content-Type: application/json
Authorization: {{token}}

{
	"id": 1
}
###

GET http://{{host}}/research/2024-3-6/2024-3-6
Content-Type: application/json
Authorization: {{token}}
###

GET http://{{host}}/questions/binary/2024-03-14/2024-03-21
Content-Type: application/json
Authorization: {{token}}
###

POST http://{{host}}/customer
Content-Type: application/json
Authorization: {{token}}

{
	"first_name": "Geraldison",
	"surname": "Pinto",
	"position": "GERENTE",
	"phone": "(61) 996778575",
	"email": "comercial.bsbdu@gmail.com",
	"password": "@Senha123",
	"accept_terms": 1,
	"company": 2,
	"role_id": 3,
	"change_password": 0
}
###

PUT http://{{host}}/customer
Content-Type: application/json
Authorization: {{token}}

{
	"id": 6,
	"first_name": "Vandicreison",
	"surname": "Pinto Sousa",
	"position": "Baixo Clero",
	"phone": "(61) 996778575",
	"role_id": 2
}
###

PATCH http://{{host}}/active-customer
Content-Type: application/json

{
	"token": "8bc7d405-50db-444d-8beb-a95bcab8c016",
	"id": 5
}
###

POST http://{{host}}/force/change/password
Content-Type: application/json
Authorization: {{token}}

{
	"change": 1
}
###