@host = localhost:3007
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDgzNTMyNjIsImV4cCI6MTcwODQzNjA2Miwic3ViIjoiMTgifQ.obiW5crfv5dUPXcL6C2aSaSbKs2wiP60-aJYOlsm4Ck

# create new user
POST http://{{host}}/department
Content-Type: application/json
Authorization: {{token}}

{
	"name": "Test Department",
	"status": 1,
	"company": 2
}
###