@host = localhost:3007
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTAwODM0MzAsImV4cCI6MTcxMDE2NjIzMCwic3ViIjoiMiJ9.DJ82HOnL7np7ntEOLdIL9PYmxeoKfgbCbJWbgU8XFwo

# create new user
POST http://{{host}}/question
Content-Type: application/json
Authorization: {{token}}

{
	"title_question": "title question",
	"tree_question": 0,
	"question_description": "test descriptions",
	"type_question": "finish",
	"status": 1,
	"text_end_research": "Ficamos muito felizes",
	"text_label_one": "label one",
	"text_label_two": "label two",
	"research_title": "test research",
	"alert_label": "alert label test",
	"company_id": 2
}
###

POST http://{{host}}/add/possible/answers
Content-Type: application/json
Authorization: {{token}}

{
	"question_id": 1,
	"answers": [
		"pombo correio",
		"carta",
		"rebolo postal",
		"carta de baixo da calcinha"
  ]
}
###


GET http://{{host}}/company-questions
Content-Type: application/json
Authorization: {{token}}
###