@host = localhost:3007
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTA1NTI0NTIsImV4cCI6MTcxMDYzNTI1Miwic3ViIjoiMiJ9.HEsa97m9E37rCxRX6PsE2zgS0bSs3ugihoxuyp3rqqU

GET http://{{host}}/departments
Content-Type: application/json
Authorization: {{token}}
###

GET http://{{host}}/company-departments
Content-Type: application/json
Authorization: {{token}}
###