@host = localhost:3007
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTMwMzQ5MjcsImV4cCI6MTcxMzExNzcyNywic3ViIjoiMiJ9.6DykegTrH_PjPwKQuZzHBsFXgp84SCzZU3nWxdVAq_c

POST http://{{host}}/answer/report
Content-Type: application/json
Authorization: {{token}}

[
	[
    { "text": "AUTOMATIZA SOLUÇÕES PARA O VAREJO LTDA", "style": "company" },
    { "text": "Data da Pesquisa: 18/03/2024 Hora: 17:59:31", "style": "periodo" },
    { "text": "Data da Impressão: 19/03/2024 Hora: 12:36:14", "style": "horario_report" },
    { "text": "Pesquisa - 202403212T200208", "style": "header" },
    { "image": "96b05cf06b9bb01e5f6e774e11e9d55f551c.2.png", "width": 190, "absolutePosition": { "x": 350, "y": 85 } },
    { "text": "Avaliação Negativa", "style": "tree", "alignment": "center" },
    { "image": "negative.png", "width": 20, "absolutePosition": { "x": 280, "y": 210 } },
    { "text": "Colaborador Indicado: GABRIEL", "style": "employee" },
    { "text": "1 - Em qual departamento você não teve uma boa experiência?", "style": "question" },
    { "text": "Resposta: Depósito", "style": "response" },
    { "text": "2 - Em qual departamento você não teve uma boa experiência?", "style": "question" },
    { "text": "Resposta: Atendimento ao Cliente", "style": "response" },
    { "text": "3 - Nos dê oportunidade de melhorar! Conte-nos com suas palavras, hora é agora.", "style": "question" },
    { "text": "Resposta: Teste", "style": "response" },
    { "text": "4 - Voltaria comprar conosco em uma nova oportunidade?", "style": "question" },
    { "text": "Resposta:VÁ TE TOMAR NO CU", "style": "response" }
	],
	[
    { "text": "AUTOMATIZA SOLUÇÕES PARA O VAREJO LTDA", "style": "company" },
    { "text": "Data da Pesquisa: 18/03/2024 Hora: 17:59:31", "style": "periodo" },
    { "text": "Data da Impressão: 19/03/2024 Hora: 12:36:14", "style": "horario_report" },
    { "text": "Pesquisa - 202403212T200218", "style": "header" },
    { "image": "377cf4b2ec10d165348f28838d6e2f3b49e0.18.png", "width": 190, "absolutePosition": { "x": 350, "y": 85 } },
    { "text": "Avaliação Negativa", "style": "tree", "alignment": "center" },
    { "image": "negative.png", "width": 20, "absolutePosition": { "x": 280, "y": 210 } },
    { "text": "Colaborador Indicado: GABRIEL", "style": "employee" },
    { "text": "1 - Em qual departamento você não teve uma boa experiência?", "style": "question" },
    { "text": "Resposta: Depósito", "style": "response" },
    { "text": "2 - Em qual departamento você não teve uma boa experiência?", "style": "question" },
    { "text": "Resposta: Atendimento ao Cliente", "style": "response" },
    { "text": "3 - Nos dê oportunidade de melhorar! Conte-nos com suas palavras, hora é agora.", "style": "question" },
    { "text": "Resposta: Teste", "style": "response" },
    { "text": "4 - Voltaria comprar conosco em uma nova oportunidade?", "style": "question" },
    { "text": "Resposta:VÁ TE TOMAR NO CU", "style": "response" }
	]
]
###

,
	# [
    # { "text": "AUTOMATIZA SOLUÇÕES PARA O VAREJO LTDA", "style": "company" },
    # { "text": "Data da Pesquisa: 18/03/2024 Hora: 17:59:31", "style": "periodo" },
    # { "text": "Data da Impressão: 19/03/2024 Hora: 12:36:14", "style": "horario_report" },
    # { "text": "Pesquisa - 202403212T200218", "style": "header" },
    # { "image": "377cf4b2ec10d165348f28838d6e2f3b49e0.18.png", "width": 190, "absolutePosition": { "x": 350, "y": 85 } },
    # { "text": "Avaliação Negativa", "style": "tree", "alignment": "center" },
    # { "image": "negative.png", "width": 20, "absolutePosition": { "x": 280, "y": 210 } },
    # { "text": "Colaborador Indicado: GABRIEL", "style": "employee" },
    # { "text": "1 - Em qual departamento você não teve uma boa experiência?", "style": "question" },
    # { "text": "Resposta: Depósito", "style": "response" },
    # { "text": "2 - Em qual departamento você não teve uma boa experiência?", "style": "question" },
    # { "text": "Resposta: Atendimento ao Cliente", "style": "response" },
    # { "text": "3 - Nos dê oportunidade de melhorar! Conte-nos com suas palavras, hora é agora.", "style": "question" },
    # { "text": "Resposta: Teste", "style": "response" },
    # { "text": "4 - Voltaria comprar conosco em uma nova oportunidade?", "style": "question" },
    # { "text": "Resposta:VÁ TE TOMAR NO CU", "style": "response" }
	# ]