
@host = localhost:3007

POST http://{{host}}/session
Content-Type: application/json

{
	"email": "comercial@automatizavarejo.com.br",
	"password": "@Teste1234"
}
###

# {
# 	"email": "goncalina23@hotmail.com",
# 	"password": "@Goncalina123"
# }

# {
# 	"email": "comercial@automatizavarejo.com.br",
# 	"password": "@Teste1234"
# }

# {
# 	"email": "pediegoss@gmail.com",
# 	"password": "@senha123"
# }

# {
# 	"email": "joerlison@gmail.com",
# 	"password": "@senha123"
# }

# {
# 	"email": "lords.gaps@gmail.com",
# 	"password": "123"
# }